// Auto-generated by parse_sqm.py
// Faction: =BTC= Russian Winter Force

class GVAR(russian_winter_force_rhs_msv_emr_officer) : rhs_msv_emr_officer {
	displayName = "Squad Leader";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_rhs_msv_emr_officer.jpg);
	faction = QGVAR(russian_winter_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "VSM_Balaclava_black_Goggles", "UK3CB_Tactical_Gloves_black_NVG"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "VSM_Balaclava_black_Goggles", "UK3CB_Tactical_Gloves_black_NVG"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK"};
	respawnWeapons[] = {QGVAR(flashlight_sight_rhs_weap_ak74m_desert_npz), "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
	uniformClass = "UK3CB_CHD_W_B_U_CombatSmock_12";
	vehicleClass = "Men";
	weapons[] = {QGVAR(flashlight_sight_rhs_weap_ak74m_desert_npz), "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
};
class GVAR(russian_winter_force_O_Soldier_TL_F) : O_Soldier_TL_F {
	displayName = "Team Leader";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_O_Soldier_TL_F.jpg);
	faction = QGVAR(russian_winter_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "UK3CB_G_Balaclava_Win_04", "UK3CB_Tactical_Gloves_black_NVG"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "UK3CB_G_Balaclava_Win_04", "UK3CB_Tactical_Gloves_black_NVG"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y"};
	respawnWeapons[] = {"UK3CB_FAMAS_F1", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
	uniformClass = "UK3CB_CHD_W_B_U_CombatSmock_07";
	vehicleClass = "Men";
	weapons[] = {"UK3CB_FAMAS_F1", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
};
class GVAR(russian_winter_force_O_Soldier_LAT_F) : O_Soldier_LAT_F {
	displayName = "AT Rifleman";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_O_Soldier_LAT_F.jpg);
	faction = QGVAR(russian_winter_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "VSM_Balaclava2_black_Peltor_Goggles", "UK3CB_Tactical_Gloves_black_NVG"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_Uzi_32Rnd_Magazine_Y", "UK3CB_Uzi_32Rnd_Magazine_Y", "UK3CB_Uzi_32Rnd_Magazine_Y", "UK3CB_Uzi_32Rnd_Magazine_Y", "UK3CB_Uzi_32Rnd_Magazine_Y", "UK3CB_Uzi_32Rnd_Magazine_Y", "UK3CB_Uzi_32Rnd_Magazine_Y", "UK3CB_Uzi_32Rnd_Magazine_Y", "UK3CB_Uzi_32Rnd_Magazine_Y", "rhs_rpg7_PG7V_mag", "rhs_rpg7_PG7V_mag", "rhs_rpg7_PG7V_mag", "rhs_rpg7_PG7V_mag"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "VSM_Balaclava2_black_Peltor_Goggles", "UK3CB_Tactical_Gloves_black_NVG"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_Uzi_32Rnd_Magazine_Y", "UK3CB_Uzi_32Rnd_Magazine_Y", "UK3CB_Uzi_32Rnd_Magazine_Y", "UK3CB_Uzi_32Rnd_Magazine_Y", "UK3CB_Uzi_32Rnd_Magazine_Y", "UK3CB_Uzi_32Rnd_Magazine_Y", "UK3CB_Uzi_32Rnd_Magazine_Y", "UK3CB_Uzi_32Rnd_Magazine_Y", "UK3CB_Uzi_32Rnd_Magazine_Y", "rhs_rpg7_PG7V_mag", "rhs_rpg7_PG7V_mag", "rhs_rpg7_PG7V_mag", "rhs_rpg7_PG7V_mag"};
	respawnWeapons[] = {"UK3CB_Uzi_Stock", "rhs_weap_makarov_pm", "rhs_pdu4", "rhs_weap_rpg7", "Throw", "Put", "Binocular"};
	backpack = "UK3CB_TNM_B_B_RPG";
	uniformClass = "UK3CB_CHD_W_B_U_CombatSmock_11";
	vehicleClass = "Men";
	weapons[] = {"UK3CB_Uzi_Stock", "rhs_weap_makarov_pm", "rhs_pdu4", "rhs_weap_rpg7", "Throw", "Put", "Binocular"};
};
class GVAR(russian_winter_force_rhsgref_ins_machinegunner) : rhsgref_ins_machinegunner {
	displayName = "Machinegunner";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_rhsgref_ins_machinegunner.jpg);
	faction = QGVAR(russian_winter_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "rhsusf_shemagh2_gogg_white", "UK3CB_Tactical_Gloves_black_NVG", "UK3CB_H_Beanie_02_Win_Float_Alt"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "rhsusf_shemagh2_gogg_white", "UK3CB_Tactical_Gloves_black_NVG", "UK3CB_H_Beanie_02_Win_Float_Alt"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT"};
	respawnWeapons[] = {"UK3CB_RPD", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
	backpack = "UK3CB_CSAT_U_O_B_UMBTS";
	uniformClass = "UK3CB_CHD_W_B_U_CombatSmock_13";
	vehicleClass = "Men";
	weapons[] = {"UK3CB_RPD", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
};
class GVAR(russian_winter_force_rhsgref_ins_machinegunner_a) : rhsgref_ins_machinegunner {
	displayName = "Asst. Machinegunner";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_rhsgref_ins_machinegunner_a.jpg);
	faction = QGVAR(russian_winter_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_RECON_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "VSM_Balaclava2_black_Goggles", "UK3CB_Tactical_Gloves_black_NVG"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_RECON_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "VSM_Balaclava2_black_Goggles", "UK3CB_Tactical_Gloves_black_NVG"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT"};
	respawnWeapons[] = {QGVAR(flashlight_rhs_weap_ak74m_desert_npz), "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
	backpack = "UK3CB_CSAT_U_O_B_UMBTS";
	uniformClass = "UK3CB_CHD_W_B_U_CombatSmock_07";
	vehicleClass = "Men";
	weapons[] = {QGVAR(flashlight_rhs_weap_ak74m_desert_npz), "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
};
class GVAR(russian_winter_force_O_Soldier_F) : O_Soldier_F {
	displayName = "Rifleman";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_O_Soldier_F.jpg);
	faction = QGVAR(russian_winter_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "VSM_Balaclava2_black_Goggles", "UK3CB_Tactical_Gloves_black_NVG"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "VSM_Balaclava2_black_Goggles", "UK3CB_Tactical_Gloves_black_NVG"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y", "UK3CB_FAMAS_25rnd_556x45_Y"};
	respawnWeapons[] = {QGVAR(flashlight_UK3CB_FAMAS_F1), "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
	uniformClass = "UK3CB_CHD_W_B_U_CombatSmock_07";
	vehicleClass = "Men";
	weapons[] = {QGVAR(flashlight_UK3CB_FAMAS_F1), "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
};
class GVAR(russian_winter_force_O_Soldier_F_s) : O_Soldier_F {
	displayName = "SMG";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_O_Soldier_F_s.jpg);
	faction = QGVAR(russian_winter_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "UK3CB_G_Balaclava2_WIN", "UK3CB_Tactical_Gloves_black_NVG"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x19mm_7n21_44", "rhs_mag_9x19mm_7n21_44", "rhs_mag_9x19mm_7n21_44", "rhs_mag_9x19mm_7n21_44", "rhs_mag_9x19mm_7n21_44", "rhs_mag_9x19mm_7n21_44", "rhs_mag_9x19mm_7n21_44", "rhs_mag_9x19mm_7n21_44"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "UK3CB_G_Balaclava2_WIN", "UK3CB_Tactical_Gloves_black_NVG"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x19mm_7n21_44", "rhs_mag_9x19mm_7n21_44", "rhs_mag_9x19mm_7n21_44", "rhs_mag_9x19mm_7n21_44", "rhs_mag_9x19mm_7n21_44", "rhs_mag_9x19mm_7n21_44", "rhs_mag_9x19mm_7n21_44", "rhs_mag_9x19mm_7n21_44"};
	respawnWeapons[] = {"rhs_weap_pp2000", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
	uniformClass = "UK3CB_CHD_W_B_U_CombatSmock_07";
	vehicleClass = "Men";
	weapons[] = {"rhs_weap_pp2000", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
};
class GVAR(russian_winter_force_O_Soldier_F_r) : O_Soldier_F {
	displayName = "Rifleman 2";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_O_Soldier_F_r.jpg);
	faction = QGVAR(russian_winter_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "VSM_Balaclava2_black_Goggles", "UK3CB_Tactical_Gloves_black_NVG"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "VSM_Balaclava2_black_Goggles", "UK3CB_Tactical_Gloves_black_NVG"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK"};
	respawnWeapons[] = {QGVAR(flashlight_rhs_weap_ak74m_desert_npz), "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
	uniformClass = "UK3CB_CHD_W_B_U_CombatSmock_07";
	vehicleClass = "Men";
	weapons[] = {QGVAR(flashlight_rhs_weap_ak74m_desert_npz), "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
};
class GVAR(russian_winter_force_O_soldier_M_F) : O_soldier_M_F {
	displayName = "Marksman";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_O_soldier_M_F.jpg);
	faction = QGVAR(russian_winter_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "VSM_Balaclava2_black_Goggles", "UK3CB_Tactical_Gloves_black_NVG"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "VSM_Balaclava2_black_Goggles", "UK3CB_Tactical_Gloves_black_NVG"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell"};
	respawnWeapons[] = {QGVAR(scoped_rhs_weap_svds), "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
	uniformClass = "UK3CB_CHD_W_B_U_CombatSmock_05";
	vehicleClass = "Men";
	weapons[] = {QGVAR(scoped_rhs_weap_svds), "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
};
class GVAR(russian_winter_force_O_helipilot_F) : O_helipilot_F {
	displayName = "Heli Pilot";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_O_helipilot_F.jpg);
	faction = QGVAR(russian_winter_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_Compact_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "VSM_balaclava2_Black", "UK3CB_Tactical_Gloves_black_NVG", "rhsusf_hgu56p_visor_white"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_Compact_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "VSM_balaclava2_Black", "UK3CB_Tactical_Gloves_black_NVG", "rhsusf_hgu56p_visor_white"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y"};
	respawnWeapons[] = {"UK3CB_P90C_black", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
	uniformClass = "UK3CB_CHD_W_B_U_CombatSmock_07";
	vehicleClass = "Men";
	weapons[] = {"UK3CB_P90C_black", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
};
class GVAR(russian_winter_force_O_crew_F) : O_crew_F {
	displayName = "Vehicle Crew";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_O_crew_F.jpg);
	faction = QGVAR(russian_winter_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_Compact_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "rhsusf_shemagh2_gogg_od", "UK3CB_Tactical_Gloves_black_NVG", "H_Tank_eaf_F"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_Compact_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "rhsusf_shemagh2_gogg_od", "UK3CB_Tactical_Gloves_black_NVG", "H_Tank_eaf_F"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y"};
	respawnWeapons[] = {"UK3CB_P90C_black", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
	uniformClass = "UK3CB_CHD_W_B_U_CombatSmock_07";
	vehicleClass = "Men";
	weapons[] = {"UK3CB_P90C_black", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
};
class GVAR(russian_winter_force_rhsgref_ins_arifleman_rpk) : rhsgref_ins_arifleman_rpk {
	displayName = "Autorifleman";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_rhsgref_ins_arifleman_rpk.jpg);
	faction = QGVAR(russian_winter_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_CQB_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "VSM_Balaclava2_black_Goggles", "UK3CB_Tactical_Gloves_black_NVG"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_AUG_42Rnd_556x45_Magazine_Y", "UK3CB_AUG_42Rnd_556x45_Magazine_Y", "UK3CB_AUG_42Rnd_556x45_Magazine_Y", "UK3CB_AUG_42Rnd_556x45_Magazine_Y", "UK3CB_AUG_42Rnd_556x45_Magazine_Y", "UK3CB_AUG_42Rnd_556x45_Magazine_Y", "UK3CB_AUG_42Rnd_556x45_Magazine_Y"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_CQB_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "VSM_Balaclava2_black_Goggles", "UK3CB_Tactical_Gloves_black_NVG"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_AUG_42Rnd_556x45_Magazine_Y", "UK3CB_AUG_42Rnd_556x45_Magazine_Y", "UK3CB_AUG_42Rnd_556x45_Magazine_Y", "UK3CB_AUG_42Rnd_556x45_Magazine_Y", "UK3CB_AUG_42Rnd_556x45_Magazine_Y", "UK3CB_AUG_42Rnd_556x45_Magazine_Y", "UK3CB_AUG_42Rnd_556x45_Magazine_Y"};
	respawnWeapons[] = {"uk3cb_auga2_lsw_blk", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
	backpack = "UK3CB_CSAT_U_O_B_UMBTS";
	uniformClass = "UK3CB_CHD_W_B_U_CombatSmock_07";
	vehicleClass = "Men";
	weapons[] = {"uk3cb_auga2_lsw_blk", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
};

class GVAR(russian_winter_force_UK3CB_CSAT_S_O_BRDM2) : UK3CB_CSAT_S_O_BRDM2 {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_BRDM2.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_BRDM2_ATGM) : UK3CB_CSAT_S_O_BRDM2_ATGM {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_BRDM2_ATGM.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_BRDM2_HQ) : UK3CB_CSAT_S_O_BRDM2_HQ {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_BRDM2_HQ.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_Tigr_STS) : UK3CB_CSAT_S_O_Tigr_STS {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_Tigr_STS.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
	class Turrets: Turrets {
		class MainTurret: MainTurret {
			gunnerType = QGVAR(russian_winter_force_rhs_msv_emr_officer);
		};
		class AGS_Turret: AGS_Turret {
			gunnerType = QGVAR(russian_winter_force_rhs_msv_emr_officer);
		};
	};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_Tigr_FFV) : UK3CB_CSAT_S_O_Tigr_FFV {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_Tigr_FFV.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_GAZ_Vodnik_PKT) : UK3CB_CSAT_S_O_GAZ_Vodnik_PKT {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_GAZ_Vodnik_PKT.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_GAZ_Vodnik) : UK3CB_CSAT_S_O_GAZ_Vodnik {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_GAZ_Vodnik.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_UAZ_Closed) : UK3CB_CSAT_S_O_UAZ_Closed {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_UAZ_Closed.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_Gaz66_Radio) : UK3CB_CSAT_S_O_Gaz66_Radio {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_Gaz66_Radio.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_Ural) : UK3CB_CSAT_S_O_Ural {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_Ural.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_Ural_Fuel) : UK3CB_CSAT_S_O_Ural_Fuel {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_Ural_Fuel.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_Ural_Zu23) : UK3CB_CSAT_S_O_Ural_Zu23 {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_Ural_Zu23.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
	class Turrets: Turrets {
		class MainTurret: MainTurret {
			gunnerType = QGVAR(russian_winter_force_O_Soldier_F);
		};
		class CargoTurret_01: CargoTurret_01 {
			gunnerType = QGVAR(russian_winter_force_O_Soldier_F);
		};
		class CargoTurret_02: CargoTurret_02 {
			gunnerType = QGVAR(russian_winter_force_O_Soldier_F);
		};
		class CargoTurret_03: CargoTurret_03 {
			gunnerType = QGVAR(russian_winter_force_O_Soldier_F);
		};
	};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_Ural_Ammo) : UK3CB_CSAT_S_O_Ural_Ammo {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_Ural_Ammo.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_Ural_Repair) : UK3CB_CSAT_S_O_Ural_Repair {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_Ural_Repair.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_BMP1) : UK3CB_CSAT_S_O_BMP1 {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_BMP1.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_BMP2) : UK3CB_CSAT_S_O_BMP2 {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_BMP2.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_BTR60) : UK3CB_CSAT_S_O_BTR60 {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_BTR60.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_BTR80) : UK3CB_CSAT_S_O_BTR80 {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_BTR80.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_BTR80a) : UK3CB_CSAT_S_O_BTR80a {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_BTR80a.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_Marid_Unarmed) : UK3CB_CSAT_S_O_Marid_Unarmed {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_Marid_Unarmed.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_T72BA) : UK3CB_CSAT_S_O_T72BA {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_T72BA.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
	class Turrets: Turrets {
		class MainTurret: MainTurret {
			class Turrets: Turrets {
				class CommanderMG: CommanderOptics {
					gunnerType = QGVAR(russian_winter_force_rhs_msv_emr_officer);
				};
				class CommanderOptics: CommanderOptics {
					gunnerType = QGVAR(russian_winter_force_rhs_msv_emr_officer);
				};
			};
		};
	};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_T80) : UK3CB_CSAT_S_O_T80 {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_T80.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
	class Turrets: Turrets {
		class MainTurret: MainTurret {
			class Turrets: Turrets {
				class CommanderMG: CommanderOptics {
					gunnerType = QGVAR(russian_winter_force_rhs_msv_emr_officer);
				};
				class CommanderOptics: CommanderOptics {
					gunnerType = QGVAR(russian_winter_force_rhs_msv_emr_officer);
				};
			};
		};
	};
};
class GVAR(russian_winter_force_rhs_D30_at_msv) : rhs_D30_at_msv {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_rhs_D30_at_msv.jpg);
	crew = QGVAR(russian_winter_force_O_Soldier_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_Soldier_F)};
};
class GVAR(russian_winter_force_rhs_2b14_82mm_msv) : rhs_2b14_82mm_msv {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_rhs_2b14_82mm_msv.jpg);
	crew = QGVAR(russian_winter_force_O_Soldier_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_Soldier_F)};
};
class GVAR(russian_winter_force_rhs_Kornet_9M133_2_msv) : rhs_Kornet_9M133_2_msv {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_rhs_Kornet_9M133_2_msv.jpg);
	crew = QGVAR(russian_winter_force_O_Soldier_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_Soldier_F)};
};
class GVAR(russian_winter_force_UK3CB_O_Static_PKM_High_MSV) : UK3CB_O_Static_PKM_High_MSV {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_O_Static_PKM_High_MSV.jpg);
	crew = QGVAR(russian_winter_force_O_Soldier_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_Soldier_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_PKM_nest) : UK3CB_CSAT_S_O_PKM_nest {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_PKM_nest.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_Radar_System) : UK3CB_CSAT_S_O_Radar_System {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_Radar_System.jpg);
	crew = QGVAR(russian_winter_force_O_Soldier_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_Soldier_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_RBS70) : UK3CB_CSAT_S_O_RBS70 {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_RBS70.jpg);
	crew = QGVAR(russian_winter_force_O_Soldier_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_Soldier_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_SAMS_System) : UK3CB_CSAT_S_O_SAMS_System {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_SAMS_System.jpg);
	crew = QGVAR(russian_winter_force_O_Soldier_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_Soldier_F)};
};
class GVAR(russian_winter_force_RHS_ZU23_MSV) : RHS_ZU23_MSV {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_RHS_ZU23_MSV.jpg);
	crew = QGVAR(russian_winter_force_O_Soldier_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_Soldier_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_Kajman) : UK3CB_CSAT_S_O_Kajman {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_Kajman.jpg);
	crew = QGVAR(russian_winter_force_O_helipilot_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_helipilot_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_Mi_24G) : UK3CB_CSAT_S_O_Mi_24G {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_Mi_24G.jpg);
	crew = QGVAR(russian_winter_force_O_helipilot_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_helipilot_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_Mi8AMTSh) : UK3CB_CSAT_S_O_Mi8AMTSh {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_Mi8AMTSh.jpg);
	crew = QGVAR(russian_winter_force_O_helipilot_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_helipilot_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_Mi8) : UK3CB_CSAT_S_O_Mi8 {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_Mi8.jpg);
	crew = QGVAR(russian_winter_force_O_helipilot_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_helipilot_F)};
};
class GVAR(russian_winter_force_UK3CB_CSAT_S_O_Mi8AMT) : UK3CB_CSAT_S_O_Mi8AMT {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CSAT_S_O_Mi8AMT.jpg);
	crew = QGVAR(russian_winter_force_O_helipilot_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_helipilot_F)};
};
class GVAR(russian_winter_force_UK3CB_CW_SOV_O_EARLY_Antonov_AN2) : UK3CB_CW_SOV_O_EARLY_Antonov_AN2 {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_UK3CB_CW_SOV_O_EARLY_Antonov_AN2.jpg);
	crew = QGVAR(russian_winter_force_O_crew_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_crew_F)};
	hiddenSelectionsTextures[] = {"UK3CB_Factions\addons\UK3CB_Factions_Vehicles\air\UK3CB_Factions_Vehicles_AN2\data\an2_1_gray_co.paa","UK3CB_Factions\addons\UK3CB_Factions_Vehicles\air\UK3CB_Factions_Vehicles_AN2\data\an2_2_gray_co.paa","UK3CB_Factions\addons\UK3CB_Factions_Vehicles\air\UK3CB_Factions_Vehicles_AN2\data\an2_wings_gray_co.paa"};
};
class GVAR(russian_winter_force_rhs_mig29sm_vvs) : rhs_mig29sm_vvs {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_rhs_mig29sm_vvs.jpg);
	crew = QGVAR(russian_winter_force_O_helipilot_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_helipilot_F)};
};
class GVAR(russian_winter_force_RHS_Su25SM_vvs) : RHS_Su25SM_vvs {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_RHS_Su25SM_vvs.jpg);
	crew = QGVAR(russian_winter_force_O_helipilot_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_helipilot_F)};
	hiddenselectionstextures[] = {"\rhsafrf\addons\rhs_a2port_air\su25\data\su25_body1_alt_co.paa","\rhsafrf\addons\rhs_a2port_air\su25\data\su25_body2_alt_co.paa","a3\data_f\clear_empty.paa","a3\data_f\clear_empty.paa","a3\data_f\clear_empty.paa","a3\data_f\clear_empty.paa","rhsafrf\addons\rhs_decals\data\labels\aviation\vvs_ca.paa"};
};
class GVAR(russian_winter_force_RHS_T50_vvs_054) : RHS_T50_vvs_054 {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_RHS_T50_vvs_054.jpg);
	crew = QGVAR(russian_winter_force_O_helipilot_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_helipilot_F)};
};
class GVAR(russian_winter_force_RHS_TU95MS_vvs_chelyabinsk) : RHS_TU95MS_vvs_chelyabinsk {
	editorPreview = QPATHTOF(data\editorPreviews\russian_winter_force_RHS_TU95MS_vvs_chelyabinsk.jpg);
	crew = QGVAR(russian_winter_force_O_helipilot_F);
	faction = QGVAR(russian_winter_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_winter_force_O_helipilot_F)};
};
