// Auto-generated by parse_sqm.py
// Faction: =BTC= Shadow Company

class GVAR(shadow_company) {
	name = "=BTC= Shadow Company";
	class Infantry {
		name = "Infantry";
		class assault_squad {
			faction = QGVAR(shadow_company);
			icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
			name = "Assault Squad";
			side = 0;
			class unit0 {
				position[] = {0.0, 0.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(shadow_company_O_Soldier_SL_F);
			};
			class unit1 {
				position[] = {-1.5, -2.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(shadow_company_O_Soldier_TL_F);
			};
			class unit2 {
				position[] = {1.5, -2.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(shadow_company_O_Soldier_LAT_F);
			};
			class unit3 {
				position[] = {-3.0, -5.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(shadow_company_rhsgref_ins_machinegunner);
			};
			class unit4 {
				position[] = {3.0, -5.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(shadow_company_O_Soldier_AAR_F);
			};
			class unit5 {
				position[] = {-4.5, -7.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(shadow_company_O_Soldier_F);
			};
			class unit6 {
				position[] = {4.5, -7.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(shadow_company_O_Soldier_F);
			};
			class unit7 {
				position[] = {-6.0, -10.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(shadow_company_O_soldier_M_F);
			};
			class unit8 {
				position[] = {6.0, -10.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(shadow_company_O_Soldier_F);
			};
		};
		class fire_team {
			faction = QGVAR(shadow_company);
			icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
			name = "Fire Team";
			side = 0;
			class unit0 {
				position[] = {0.0, 0.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(shadow_company_O_Soldier_TL_F);
			};
			class unit1 {
				position[] = {-1.5, -2.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(shadow_company_O_Soldier_LAT_F);
			};
			class unit2 {
				position[] = {1.5, -2.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(shadow_company_O_Soldier_F);
			};
			class unit3 {
				position[] = {-3.0, -5.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(shadow_company_O_Soldier_F);
			};
		};
		class cqb_team {
			faction = QGVAR(shadow_company);
			icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
			name = "CQB Team";
			side = 0;
			class unit0 {
				position[] = {0.0, 0.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(shadow_company_O_Soldier_TL_F);
			};
			class unit1 {
				position[] = {-1.5, -2.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(shadow_company_O_Soldier_F);
			};
			class unit2 {
				position[] = {1.5, -2.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(shadow_company_O_Soldier_TL_F);
			};
			class unit3 {
				position[] = {-3.0, -5.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(shadow_company_O_Soldier_TL_F);
			};
		};
		class support_squad {
			faction = QGVAR(shadow_company);
			icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
			name = "Support Squad";
			side = 0;
			class unit0 {
				position[] = {0.0, 0.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(shadow_company_O_Soldier_SL_F);
			};
			class unit1 {
				position[] = {-1.5, -2.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(shadow_company_rhsgref_ins_machinegunner);
			};
			class unit2 {
				position[] = {1.5, -2.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(shadow_company_O_Soldier_AAR_F);
			};
			class unit3 {
				position[] = {-3.0, -5.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(shadow_company_O_soldier_M_F);
			};
		};
		class sentry {
			faction = QGVAR(shadow_company);
			icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
			name = "Sentry";
			side = 0;
			class unit0 {
				position[] = {0.0, 0.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(shadow_company_O_Soldier_SL_F);
			};
			class unit1 {
				position[] = {-1.5, -2.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(shadow_company_O_Soldier_F);
			};
		};
	};
};
