// Auto-generated by parse_sqm.py
// Faction: =BTC= Russian Invasion Force

class GVAR(russian_invasion_force_rhs_msv_emr_officer) : rhs_msv_emr_officer {
	displayName = "Squad Leader";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhs_msv_emr_officer.jpg);
	faction = QGVAR(russian_invasion_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "rhsusf_oakley_goggles_clr", "UK3CB_Tactical_Gloves_black_NVG", "UK3CB_CSAT_U_O_H_6b47_Bare_BLK"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "rhsusf_oakley_goggles_clr", "UK3CB_Tactical_Gloves_black_NVG", "UK3CB_CSAT_U_O_H_6b47_Bare_BLK"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell"};
	respawnWeapons[] = {QGVAR(sight_rhs_weap_ak74m_desert_npz), "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
	uniformClass = "UK3CB_CSAT_U_O_U_SF_CombatSmock_02_URB";
	vehicleClass = "Men";
	weapons[] = {QGVAR(sight_rhs_weap_ak74m_desert_npz), "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
};
class GVAR(russian_invasion_force_O_Soldier_TL_F) : O_Soldier_TL_F {
	displayName = "Team Leader";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_O_Soldier_TL_F.jpg);
	faction = QGVAR(russian_invasion_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "rhsusf_oakley_goggles_clr", "UK3CB_Tactical_Gloves_black_NVG", "UK3CB_CSAT_U_O_H_6b47_Bare_BLK"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "rhsusf_oakley_goggles_clr", "UK3CB_Tactical_Gloves_black_NVG", "UK3CB_CSAT_U_O_H_6b47_Bare_BLK"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell"};
	respawnWeapons[] = {QGVAR(sight_rhs_weap_ak74m_desert_npz), "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
	uniformClass = "UK3CB_CSAT_U_O_U_SF_CombatSmock_02_URB";
	vehicleClass = "Men";
	weapons[] = {QGVAR(sight_rhs_weap_ak74m_desert_npz), "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
};
class GVAR(russian_invasion_force_O_Soldier_LAT_F) : O_Soldier_LAT_F {
	displayName = "AT Rifleman";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_O_Soldier_LAT_F.jpg);
	faction = QGVAR(russian_invasion_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "kat_mask_M50", "UK3CB_Tactical_Gloves_black_NVG", "UK3CB_CSAT_U_O_H_6b47_ess_bala_URB"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_rpg7_PG7V_mag", "rhs_rpg7_PG7V_mag", "rhs_rpg7_PG7V_mag", "rhs_rpg7_PG7V_mag"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "kat_mask_M50", "UK3CB_Tactical_Gloves_black_NVG", "UK3CB_CSAT_U_O_H_6b47_ess_bala_URB"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_rpg7_PG7V_mag", "rhs_rpg7_PG7V_mag", "rhs_rpg7_PG7V_mag", "rhs_rpg7_PG7V_mag"};
	respawnWeapons[] = {QGVAR(sight_rhs_weap_ak74m_desert_npz), "rhs_weap_makarov_pm", "rhs_pdu4", "rhs_weap_rpg7", "Throw", "Put", "Binocular"};
	backpack = "UK3CB_TNM_B_B_RPG";
	uniformClass = "UK3CB_CSAT_U_O_U_SF_CombatSmock_02_URB";
	vehicleClass = "Men";
	weapons[] = {QGVAR(sight_rhs_weap_ak74m_desert_npz), "rhs_weap_makarov_pm", "rhs_pdu4", "rhs_weap_rpg7", "Throw", "Put", "Binocular"};
};
class GVAR(russian_invasion_force_rhsgref_ins_machinegunner) : rhsgref_ins_machinegunner {
	displayName = "Machinegunner";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhsgref_ins_machinegunner.jpg);
	faction = QGVAR(russian_invasion_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "rhsusf_oakley_goggles_clr", "UK3CB_Tactical_Gloves_black_NVG", "UK3CB_CSAT_U_O_H_6b47_bala_URB"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "rhsusf_oakley_goggles_clr", "UK3CB_Tactical_Gloves_black_NVG", "UK3CB_CSAT_U_O_H_6b47_bala_URB"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT"};
	respawnWeapons[] = {"UK3CB_RPD", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
	backpack = "UK3CB_CSAT_U_O_B_UMBTS";
	uniformClass = "UK3CB_CSAT_U_O_U_SF_CombatSmock_02_URB";
	vehicleClass = "Men";
	weapons[] = {"UK3CB_RPD", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
};
class GVAR(russian_invasion_force_rhsgref_ins_machinegunner_a) : rhsgref_ins_machinegunner {
	displayName = "Asst. Machinegunner";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhsgref_ins_machinegunner_a.jpg);
	faction = QGVAR(russian_invasion_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "kat_mask_M50", "UK3CB_Tactical_Gloves_black_NVG", "UK3CB_CSAT_U_O_H_6b47_ess_bala_URB"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "kat_mask_M50", "UK3CB_Tactical_Gloves_black_NVG", "UK3CB_CSAT_U_O_H_6b47_ess_bala_URB"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT", "UK3CB_RPD_100rnd_762x39_YT"};
	respawnWeapons[] = {"UK3CB_P90C_black", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
	backpack = "UK3CB_CSAT_U_O_B_UMBTS";
	uniformClass = "UK3CB_CSAT_U_O_U_SF_CombatSmock_02_URB";
	vehicleClass = "Men";
	weapons[] = {"UK3CB_P90C_black", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
};
class GVAR(russian_invasion_force_O_Soldier_F) : O_Soldier_F {
	displayName = "Rifleman";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_O_Soldier_F.jpg);
	faction = QGVAR(russian_invasion_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "kat_mask_M50", "UK3CB_Tactical_Gloves_black_NVG", "UK3CB_CSAT_U_O_H_6b47_ess_bala_URB"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "kat_mask_M50", "UK3CB_Tactical_Gloves_black_NVG", "UK3CB_CSAT_U_O_H_6b47_ess_bala_URB"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_30Rnd_545x39_7N10_desert_AK", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell"};
	respawnWeapons[] = {QGVAR(sight_rhs_weap_ak74m_desert_npz), "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
	uniformClass = "UK3CB_CSAT_U_O_U_SF_CombatSmock_02_URB";
	vehicleClass = "Men";
	weapons[] = {QGVAR(sight_rhs_weap_ak74m_desert_npz), "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
};
class GVAR(russian_invasion_force_O_Soldier_F_s) : O_Soldier_F {
	displayName = "Shotgun";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_O_Soldier_F_s.jpg);
	faction = QGVAR(russian_invasion_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "UK3CB_Tactical_Gloves_black_NVG", "UK3CB_CSAT_U_O_H_6b47_ess_bala_URB"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "uk3cb_aa12_20rnd_12g_buckshot_magazine", "uk3cb_aa12_20rnd_12g_buckshot_magazine", "uk3cb_aa12_20rnd_12g_buckshot_magazine", "uk3cb_aa12_20rnd_12g_buckshot_magazine", "uk3cb_aa12_20rnd_12g_buckshot_magazine", "uk3cb_aa12_20rnd_12g_buckshot_magazine", "uk3cb_aa12_20rnd_12g_buckshot_magazine"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "UK3CB_Tactical_Gloves_black_NVG", "UK3CB_CSAT_U_O_H_6b47_ess_bala_URB"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "uk3cb_aa12_20rnd_12g_buckshot_magazine", "uk3cb_aa12_20rnd_12g_buckshot_magazine", "uk3cb_aa12_20rnd_12g_buckshot_magazine", "uk3cb_aa12_20rnd_12g_buckshot_magazine", "uk3cb_aa12_20rnd_12g_buckshot_magazine", "uk3cb_aa12_20rnd_12g_buckshot_magazine", "uk3cb_aa12_20rnd_12g_buckshot_magazine"};
	respawnWeapons[] = {"UK3CB_AA12", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
	uniformClass = "UK3CB_CSAT_U_O_U_SF_CombatSmock_02_URB";
	vehicleClass = "Men";
	weapons[] = {"UK3CB_AA12", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
};
class GVAR(russian_invasion_force_O_Soldier_F_2) : O_Soldier_F {
	displayName = "SMG";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_O_Soldier_F_2.jpg);
	faction = QGVAR(russian_invasion_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "kat_mask_M50", "UK3CB_Tactical_Gloves_black_NVG", "UK3CB_CSAT_U_O_H_6b47_ess_bala_URB"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "kat_mask_M50", "UK3CB_Tactical_Gloves_black_NVG", "UK3CB_CSAT_U_O_H_6b47_ess_bala_URB"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y"};
	respawnWeapons[] = {"UK3CB_P90C_black", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
	uniformClass = "UK3CB_CSAT_U_O_U_SF_CombatSmock_02_URB";
	vehicleClass = "Men";
	weapons[] = {"UK3CB_P90C_black", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
};
class GVAR(russian_invasion_force_O_soldier_M_F) : O_soldier_M_F {
	displayName = "Marksman";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_O_soldier_M_F.jpg);
	faction = QGVAR(russian_invasion_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "UK3CB_Tactical_Gloves_black_NVG", "UK3CB_CSAT_U_O_H_6b47_ess_bala_URB"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "UK3CB_Tactical_Gloves_black_NVG", "UK3CB_CSAT_U_O_H_6b47_ess_bala_URB"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell"};
	respawnWeapons[] = {QGVAR(scoped_rhs_weap_svds), "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
	uniformClass = "UK3CB_CSAT_U_O_U_SF_CombatSmock_02_URB";
	vehicleClass = "Men";
	weapons[] = {QGVAR(scoped_rhs_weap_svds), "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
};
class GVAR(russian_invasion_force_O_helipilot_F) : O_helipilot_F {
	displayName = "Heli Pilot";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_O_helipilot_F.jpg);
	faction = QGVAR(russian_invasion_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_Compact_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "UK3CB_Tactical_Gloves_black_NVG", "rhsusf_hgu56p_visor_mask_tan"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_Compact_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "UK3CB_Tactical_Gloves_black_NVG", "rhsusf_hgu56p_visor_mask_tan"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y"};
	respawnWeapons[] = {"UK3CB_P90C_black", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
	uniformClass = "UK3CB_CSAT_U_O_U_SF_CombatSmock_02_URB";
	vehicleClass = "Men";
	weapons[] = {"UK3CB_P90C_black", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
};
class GVAR(russian_invasion_force_O_crew_F) : O_crew_F {
	displayName = "Vehicle Crew";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_O_crew_F.jpg);
	faction = QGVAR(russian_invasion_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_Compact_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "rhsusf_shemagh2_gogg_od", "UK3CB_Tactical_Gloves_black_NVG", "H_Tank_eaf_F"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_Compact_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "rhsusf_shemagh2_gogg_od", "UK3CB_Tactical_Gloves_black_NVG", "H_Tank_eaf_F"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y", "UK3CB_P90_50rnd_570x28_Magazine_Y"};
	respawnWeapons[] = {"UK3CB_P90C_black", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
	uniformClass = "UK3CB_CSAT_U_O_U_SF_CombatSmock_02_URB";
	vehicleClass = "Men";
	weapons[] = {"UK3CB_P90C_black", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
};
class GVAR(russian_invasion_force_rhsgref_ins_arifleman_rpk) : rhsgref_ins_arifleman_rpk {
	displayName = "Autorifleman";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhsgref_ins_arifleman_rpk.jpg);
	faction = QGVAR(russian_invasion_force);
	items[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	linkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "kat_mask_M04", "UK3CB_Tactical_Gloves_black_NVG", "UK3CB_CSAT_U_O_H_6b47_bala_URB"};
	magazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_RPK74_60rnd_545x39_YT", "UK3CB_RPK74_60rnd_545x39_YT", "UK3CB_RPK74_60rnd_545x39_YT", "UK3CB_RPK74_60rnd_545x39_YT", "UK3CB_RPK74_60rnd_545x39_YT", "UK3CB_RPK74_60rnd_545x39_YT", "UK3CB_RPK74_60rnd_545x39_YT", "UK3CB_RPK74_60rnd_545x39_YT", "UK3CB_RPK74_60rnd_545x39_YT", "UK3CB_RPK74_60rnd_545x39_YT"};
	respawnItems[] = {"FirstAidKit", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
	respawnLinkedItems[] = {"UK3CB_V_Carrier_Rig_Light_BLK", "ItemMap", "ItemRadio", "ItemWatch", "ItemCompass", "kat_mask_M04", "UK3CB_Tactical_Gloves_black_NVG", "UK3CB_CSAT_U_O_H_6b47_bala_URB"};
	respawnMagazines[] = {"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_9x18_8_57N181S", "rhs_mag_f1", "rhs_mag_f1", "SmokeShell", "SmokeShell", "SmokeShell", "UK3CB_RPK74_60rnd_545x39_YT", "UK3CB_RPK74_60rnd_545x39_YT", "UK3CB_RPK74_60rnd_545x39_YT", "UK3CB_RPK74_60rnd_545x39_YT", "UK3CB_RPK74_60rnd_545x39_YT", "UK3CB_RPK74_60rnd_545x39_YT", "UK3CB_RPK74_60rnd_545x39_YT", "UK3CB_RPK74_60rnd_545x39_YT", "UK3CB_RPK74_60rnd_545x39_YT", "UK3CB_RPK74_60rnd_545x39_YT"};
	respawnWeapons[] = {"UK3CB_RPK_74_BLK", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
	backpack = "UK3CB_CSAT_U_O_B_UMBTS";
	uniformClass = "UK3CB_CSAT_U_O_U_SF_CombatSmock_02_URB";
	vehicleClass = "Men";
	weapons[] = {"UK3CB_RPK_74_BLK", "rhs_weap_makarov_pm", "rhs_pdu4", "Throw", "Put", "Binocular"};
};

class GVAR(russian_invasion_force_rhs_tigr_3camo_vdv) : rhs_tigr_3camo_vdv {
	crew = QGVAR(russian_invasion_force_O_Soldier_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_Soldier_F)};
	editorSubcategory = "EdSubcat_Cars";
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhs_tigr_3camo_vdv.jpg);
};
class GVAR(russian_invasion_force_rhs_tigr_sts_3camo_vdv) : rhs_tigr_sts_3camo_vdv {
	crew = QGVAR(russian_invasion_force_O_Soldier_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_Soldier_F)};
	editorSubcategory = "EdSubcat_Cars";
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhs_tigr_sts_3camo_vdv.jpg);
};
class GVAR(russian_invasion_force_rhs_uaz_open_vdv) : rhs_uaz_open_vdv {
	crew = QGVAR(russian_invasion_force_O_Soldier_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_Soldier_F)};
	editorSubcategory = "EdSubcat_Cars";
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhs_uaz_open_vdv.jpg);
};
class GVAR(russian_invasion_force_rhsgref_BRDM2_vdv) : rhsgref_BRDM2_vdv {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhsgref_BRDM2_vdv.jpg);
	crew = QGVAR(russian_invasion_force_O_crew_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_crew_F)};
};
class GVAR(russian_invasion_force_rhsgref_BRDM2_ATGM_vdv) : rhsgref_BRDM2_ATGM_vdv {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhsgref_BRDM2_ATGM_vdv.jpg);
	crew = QGVAR(russian_invasion_force_O_crew_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_crew_F)};
};
class GVAR(russian_invasion_force_rhsgref_BRDM2_HQ_vdv) : rhsgref_BRDM2_HQ_vdv {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhsgref_BRDM2_HQ_vdv.jpg);
	crew = QGVAR(russian_invasion_force_O_crew_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_crew_F)};
};
class GVAR(russian_invasion_force_UK3CB_ARD_O_GAZ_Vodnik_PKT) : UK3CB_ARD_O_GAZ_Vodnik_PKT {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_UK3CB_ARD_O_GAZ_Vodnik_PKT.jpg);
	crew = QGVAR(russian_invasion_force_O_crew_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_crew_F)};
};
class GVAR(russian_invasion_force_UK3CB_ARD_O_GAZ_Vodnik) : UK3CB_ARD_O_GAZ_Vodnik {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_UK3CB_ARD_O_GAZ_Vodnik.jpg);
	crew = QGVAR(russian_invasion_force_O_crew_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_crew_F)};
};
class GVAR(russian_invasion_force_rhs_gaz66_r142_vdv) : rhs_gaz66_r142_vdv {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhs_gaz66_r142_vdv.jpg);
	crew = QGVAR(russian_invasion_force_O_Soldier_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_Soldier_F)};
};
class GVAR(russian_invasion_force_RHS_Ural_VDV_01) : RHS_Ural_VDV_01 {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_RHS_Ural_VDV_01.jpg);
	crew = QGVAR(russian_invasion_force_O_Soldier_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_Soldier_F)};
};
class GVAR(russian_invasion_force_RHS_Ural_Ammo_VDV_01) : RHS_Ural_Ammo_VDV_01 {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_RHS_Ural_Ammo_VDV_01.jpg);
	crew = QGVAR(russian_invasion_force_O_Soldier_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_Soldier_F)};
};
class GVAR(russian_invasion_force_RHS_Ural_Fuel_VDV_01) : RHS_Ural_Fuel_VDV_01 {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_RHS_Ural_Fuel_VDV_01.jpg);
	crew = QGVAR(russian_invasion_force_O_Soldier_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_Soldier_F)};
};
class GVAR(russian_invasion_force_RHS_Ural_Repair_VDV_01) : RHS_Ural_Repair_VDV_01 {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_RHS_Ural_Repair_VDV_01.jpg);
	crew = QGVAR(russian_invasion_force_O_Soldier_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_Soldier_F)};
};
class GVAR(russian_invasion_force_RHS_Ural_Zu23_VDV_01) : RHS_Ural_Zu23_VDV_01 {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_RHS_Ural_Zu23_VDV_01.jpg);
	crew = QGVAR(russian_invasion_force_O_Soldier_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_Soldier_F)};
};
class GVAR(russian_invasion_force_rhs_btr60_vdv) : rhs_btr60_vdv {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhs_btr60_vdv.jpg);
	crew = QGVAR(russian_invasion_force_O_crew_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_crew_F)};
};
class GVAR(russian_invasion_force_rhs_btr80_vdv) : rhs_btr80_vdv {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhs_btr80_vdv.jpg);
	crew = QGVAR(russian_invasion_force_O_crew_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_crew_F)};
};
class GVAR(russian_invasion_force_rhs_btr80a_vdv) : rhs_btr80a_vdv {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhs_btr80a_vdv.jpg);
	crew = QGVAR(russian_invasion_force_O_crew_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_crew_F)};
};
class GVAR(russian_invasion_force_rhs_bmp1_vdv) : rhs_bmp1_vdv {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhs_bmp1_vdv.jpg);
	crew = QGVAR(russian_invasion_force_O_crew_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_crew_F)};
};
class GVAR(russian_invasion_force_rhs_bmp2d_vdv) : rhs_bmp2d_vdv {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhs_bmp2d_vdv.jpg);
	crew = QGVAR(russian_invasion_force_O_crew_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_crew_F)};
};
class GVAR(russian_invasion_force_rhs_t72bc_tv) : rhs_t72bc_tv {
	crew = QGVAR(russian_invasion_force_O_crew_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_crew_F)};
	class Turrets: Turrets {
		class MainTurret: MainTurret {
			class Turrets: Turrets {
				class CommanderMG: CommanderOptics {
					gunnerType = QGVAR(russian_invasion_force_rhs_msv_emr_officer);
				};
				class CommanderOptics: CommanderOptics {
					gunnerType = QGVAR(russian_invasion_force_rhs_msv_emr_officer);
				};
			};
		};
	};
	editorSubcategory = "EdSubcat_Tanks";
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhs_t72bc_tv.jpg);
};
class GVAR(russian_invasion_force_rhs_t80bk) : rhs_t80bk {
	crew = QGVAR(russian_invasion_force_O_crew_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_crew_F)};
	class Turrets: Turrets {
		class MainTurret: MainTurret {
			class Turrets: Turrets {
				class CommanderMG: CommanderMG {
					gunnerType = QGVAR(russian_invasion_force_rhs_msv_emr_officer);
				};
				class CommanderOptics: CommanderOptics {
					gunnerType = QGVAR(russian_invasion_force_rhs_msv_emr_officer);
				};
			};
		};
	};
	editorSubcategory = "EdSubcat_Tanks";
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhs_t80bk.jpg);
};
class GVAR(russian_invasion_force_rhs_Metis_9k115_2_msv) : rhs_Metis_9k115_2_msv {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhs_Metis_9k115_2_msv.jpg);
	crew = QGVAR(russian_invasion_force_O_Soldier_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_Soldier_F)};
};
class GVAR(russian_invasion_force_rhs_Kornet_9M133_2_msv) : rhs_Kornet_9M133_2_msv {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhs_Kornet_9M133_2_msv.jpg);
	crew = QGVAR(russian_invasion_force_O_Soldier_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_Soldier_F)};
};
class GVAR(russian_invasion_force_rhs_Igla_AA_pod_msv) : rhs_Igla_AA_pod_msv {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhs_Igla_AA_pod_msv.jpg);
	crew = QGVAR(russian_invasion_force_O_Soldier_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_Soldier_F)};
};
class GVAR(russian_invasion_force_UK3CB_O_Static_PKM_High_MSV) : UK3CB_O_Static_PKM_High_MSV {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_UK3CB_O_Static_PKM_High_MSV.jpg);
	crew = QGVAR(russian_invasion_force_O_Soldier_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_Soldier_F)};
};
class GVAR(russian_invasion_force_RHS_ZU23_MSV) : RHS_ZU23_MSV {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_RHS_ZU23_MSV.jpg);
	crew = QGVAR(russian_invasion_force_O_Soldier_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_Soldier_F)};
};
class GVAR(russian_invasion_force_rhs_D30_at_msv) : rhs_D30_at_msv {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhs_D30_at_msv.jpg);
	crew = QGVAR(russian_invasion_force_O_Soldier_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_Soldier_F)};
};
class GVAR(russian_invasion_force_rhs_2b14_82mm_msv) : rhs_2b14_82mm_msv {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhs_2b14_82mm_msv.jpg);
	crew = QGVAR(russian_invasion_force_O_Soldier_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_Soldier_F)};
};
class GVAR(russian_invasion_force_RHS_Mi8mt_vdv) : RHS_Mi8mt_vdv {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_RHS_Mi8mt_vdv.jpg);
	crew = QGVAR(russian_invasion_force_O_helipilot_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_helipilot_F)};
};
class GVAR(russian_invasion_force_RHS_Mi8MTV3_vdv) : RHS_Mi8MTV3_vdv {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_RHS_Mi8MTV3_vdv.jpg);
	crew = QGVAR(russian_invasion_force_O_helipilot_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_helipilot_F)};
};
class GVAR(russian_invasion_force_RHS_Mi8T_vdv) : RHS_Mi8T_vdv {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_RHS_Mi8T_vdv.jpg);
	crew = QGVAR(russian_invasion_force_O_helipilot_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_helipilot_F)};
};
class GVAR(russian_invasion_force_RHS_Mi24V_vdv) : RHS_Mi24V_vdv {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_RHS_Mi24V_vdv.jpg);
	crew = QGVAR(russian_invasion_force_O_helipilot_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_helipilot_F)};
};
class GVAR(russian_invasion_force_RHS_Ka52_vvs) : RHS_Ka52_vvs {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_RHS_Ka52_vvs.jpg);
	crew = QGVAR(russian_invasion_force_O_helipilot_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_helipilot_F)};
};
class GVAR(russian_invasion_force_RHS_TU95MS_vvs_chelyabinsk) : RHS_TU95MS_vvs_chelyabinsk {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_RHS_TU95MS_vvs_chelyabinsk.jpg);
	crew = QGVAR(russian_invasion_force_O_helipilot_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_helipilot_F)};
};
class GVAR(russian_invasion_force_RHS_T50_vvs_054) : RHS_T50_vvs_054 {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_RHS_T50_vvs_054.jpg);
	crew = QGVAR(russian_invasion_force_O_helipilot_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_helipilot_F)};
};
class GVAR(russian_invasion_force_RHS_Su25SM_vvs) : RHS_Su25SM_vvs {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_RHS_Su25SM_vvs.jpg);
	crew = QGVAR(russian_invasion_force_O_helipilot_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_helipilot_F)};
};
class GVAR(russian_invasion_force_rhs_mig29sm_vvs) : rhs_mig29sm_vvs {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_rhs_mig29sm_vvs.jpg);
	crew = QGVAR(russian_invasion_force_O_helipilot_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_helipilot_F)};
};
class GVAR(russian_invasion_force_UK3CB_CW_SOV_O_EARLY_Antonov_AN2) : UK3CB_CW_SOV_O_EARLY_Antonov_AN2 {
	editorPreview = QPATHTOF(data\editorPreviews\russian_invasion_force_UK3CB_CW_SOV_O_EARLY_Antonov_AN2.jpg);
	crew = QGVAR(russian_invasion_force_O_helipilot_F);
	faction = QGVAR(russian_invasion_force);
	side = 0;
	typicalCrew[] = {QGVAR(russian_invasion_force_O_helipilot_F)};
};
