// Auto-generated by parse_sqm.py
// Faction: =BTC= Russian Winter Force

class GVAR(russian_winter_force) {
	name = "=BTC= Russian Winter Force";
	class Infantry {
		name = "Infantry";
		class assault_squad {
			faction = QGVAR(russian_winter_force);
			icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
			name = "Assault Squad";
			side = 0;
			class unit0 {
				position[] = {0.0, 0.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_rhs_msv_emr_officer);
			};
			class unit1 {
				position[] = {-1.5, -2.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_O_Soldier_TL_F);
			};
			class unit2 {
				position[] = {1.5, -2.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_O_Soldier_LAT_F);
			};
			class unit3 {
				position[] = {-3.0, -5.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_rhsgref_ins_machinegunner);
			};
			class unit4 {
				position[] = {3.0, -5.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_O_Soldier_F);
			};
			class unit5 {
				position[] = {-4.5, -7.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_O_soldier_M_F);
			};
			class unit6 {
				position[] = {4.5, -7.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_rhsgref_ins_arifleman_rpk);
			};
			class unit7 {
				position[] = {-6.0, -10.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_rhsgref_ins_machinegunner);
			};
			class unit8 {
				position[] = {6.0, -10.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_O_Soldier_F);
			};
			class unit9 {
				position[] = {-7.5, -12.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_O_Soldier_F);
			};
		};
		class fire_team {
			faction = QGVAR(russian_winter_force);
			icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
			name = "Fire Team";
			side = 0;
			class unit0 {
				position[] = {0.0, 0.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_O_Soldier_TL_F);
			};
			class unit1 {
				position[] = {-1.5, -2.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_O_Soldier_F);
			};
			class unit2 {
				position[] = {1.5, -2.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_rhsgref_ins_arifleman_rpk);
			};
			class unit3 {
				position[] = {-3.0, -5.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_O_Soldier_F);
			};
		};
		class cqb_team {
			faction = QGVAR(russian_winter_force);
			icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
			name = "CQB Team";
			side = 0;
			class unit0 {
				position[] = {0.0, 0.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_O_Soldier_TL_F);
			};
			class unit1 {
				position[] = {-1.5, -2.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_O_Soldier_F);
			};
			class unit2 {
				position[] = {1.5, -2.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_O_Soldier_F);
			};
			class unit3 {
				position[] = {-3.0, -5.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_O_Soldier_F);
			};
		};
		class at_team {
			faction = QGVAR(russian_winter_force);
			icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
			name = "AT Team";
			side = 0;
			class unit0 {
				position[] = {0.0, 0.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_O_Soldier_TL_F);
			};
			class unit1 {
				position[] = {-1.5, -2.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_O_Soldier_LAT_F);
			};
			class unit2 {
				position[] = {1.5, -2.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_O_Soldier_F);
			};
			class unit3 {
				position[] = {-3.0, -5.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_rhsgref_ins_arifleman_rpk);
			};
		};
		class support_team {
			faction = QGVAR(russian_winter_force);
			icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
			name = "Support Team";
			side = 0;
			class unit0 {
				position[] = {0.0, 0.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_O_Soldier_TL_F);
			};
			class unit1 {
				position[] = {-1.5, -2.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_rhsgref_ins_machinegunner);
			};
			class unit2 {
				position[] = {1.5, -2.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_rhsgref_ins_machinegunner);
			};
			class unit3 {
				position[] = {-3.0, -5.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_O_soldier_M_F);
			};
		};
		class sentry {
			faction = QGVAR(russian_winter_force);
			icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
			name = "Sentry";
			side = 0;
			class unit0 {
				position[] = {0.0, 0.0, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_rhs_msv_emr_officer);
			};
			class unit1 {
				position[] = {-1.5, -2.5, 0};
				rank = "CORPORAL";
				side = 0;
				vehicle = QGVAR(russian_winter_force_O_Soldier_F);
			};
		};
	};
};
