// Auto-generated by parse_sqm.py
// Faction: =BTC= Shadow Company

class GVAR(shadow_company_O_Soldier_SL_F) : O_Soldier_SL_F {
	displayName = "Squad Leader";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_O_Soldier_SL_F.jpg);
	faction = QGVAR(shadow_company);
	items[] = {"FirstAidKit", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_Canteen", "ACE_Flashlight_MX991"};
	linkedItems[] = {"VSM_LBT6094_operator_OGA", "ItemMap", "TFAR_anprc152", "ItemWatch", "ItemCompass", "VSM_balaclava_Black", "rhsusf_ANPVS_15", "VSM_fasthelmet_black"};
	magazines[] = {"SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball"};
	respawnItems[] = {"FirstAidKit", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_Canteen", "ACE_Flashlight_MX991"};
	respawnLinkedItems[] = {"VSM_LBT6094_operator_OGA", "ItemMap", "TFAR_anprc152", "ItemWatch", "ItemCompass", "VSM_balaclava_Black", "rhsusf_ANPVS_15", "VSM_fasthelmet_black"};
	respawnMagazines[] = {"SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball"};
	respawnWeapons[] = {QGVAR(sight_laser_grip_rhs_weap_mk17_CQC), "rhsusf_weap_glock17g4", "Throw", "Put", "Binocular"};
	uniformClass = "MLO_OGA_Crye_Black_Camo";
	vehicleClass = "Men";
	weapons[] = {QGVAR(sight_laser_grip_rhs_weap_mk17_CQC), "rhsusf_weap_glock17g4", "Throw", "Put", "Binocular"};
};
class GVAR(shadow_company_O_Soldier_TL_F) : O_Soldier_TL_F {
	displayName = "Team Leader";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_O_Soldier_TL_F.jpg);
	faction = QGVAR(shadow_company);
	items[] = {"FirstAidKit", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_Canteen", "ACE_Flashlight_MX991"};
	linkedItems[] = {"VSM_CarrierRig_Operator_OGA", "ItemMap", "TFAR_anprc152", "ItemWatch", "ItemCompass", "VSM_balaclava_Black", "rhsusf_ANPVS_15", "VSM_fasthelmet_coveraor1"};
	magazines[] = {"SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_m67", "rhs_mag_m67", "UK3CB_MP5_30Rnd_10_Magazine_R", "UK3CB_MP5_30Rnd_10_Magazine_R", "UK3CB_MP5_30Rnd_10_Magazine_R"};
	respawnItems[] = {"FirstAidKit", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_Canteen", "ACE_Flashlight_MX991"};
	respawnLinkedItems[] = {"VSM_CarrierRig_Operator_OGA", "ItemMap", "TFAR_anprc152", "ItemWatch", "ItemCompass", "VSM_balaclava_Black", "rhsusf_ANPVS_15", "VSM_fasthelmet_coveraor1"};
	respawnMagazines[] = {"SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_m67", "rhs_mag_m67", "UK3CB_MP5_30Rnd_10_Magazine_R", "UK3CB_MP5_30Rnd_10_Magazine_R", "UK3CB_MP5_30Rnd_10_Magazine_R"};
	respawnWeapons[] = {"UK3CB_MP510", "rhsusf_weap_glock17g4", "Laserdesignator", "Throw", "Put", "Binocular"};
	uniformClass = "MLO_OGA_Crye_Black_Camo";
	vehicleClass = "Men";
	weapons[] = {"UK3CB_MP510", "rhsusf_weap_glock17g4", "Laserdesignator", "Throw", "Put", "Binocular"};
};
class GVAR(shadow_company_O_Soldier_LAT_F) : O_Soldier_LAT_F {
	displayName = "AT Rifleman";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_O_Soldier_LAT_F.jpg);
	faction = QGVAR(shadow_company);
	items[] = {"FirstAidKit", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_Canteen", "ACE_Flashlight_MX991"};
	linkedItems[] = {"VSM_LBT6094_breacher_OGA", "ItemMap", "TFAR_anprc152", "ItemWatch", "ItemCompass", "VSM_balaclava_Black", "rhsusf_ANPVS_15", "VSM_fasthelmet_tan"};
	magazines[] = {"SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_m67", "rhs_mag_m67"};
	respawnItems[] = {"FirstAidKit", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_Canteen", "ACE_Flashlight_MX991"};
	respawnLinkedItems[] = {"VSM_LBT6094_breacher_OGA", "ItemMap", "TFAR_anprc152", "ItemWatch", "ItemCompass", "VSM_balaclava_Black", "rhsusf_ANPVS_15", "VSM_fasthelmet_tan"};
	respawnMagazines[] = {"SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_m67", "rhs_mag_m67"};
	respawnWeapons[] = {QGVAR(sight_laser_grip_rhs_weap_mk17_CQC), "rhsusf_weap_glock17g4", "Laserdesignator", "rhs_weap_M136", "Throw", "Put", "Binocular"};
	uniformClass = "MLO_OGA_Crye_Black_Camo";
	vehicleClass = "Men";
	weapons[] = {QGVAR(sight_laser_grip_rhs_weap_mk17_CQC), "rhsusf_weap_glock17g4", "Laserdesignator", "rhs_weap_M136", "Throw", "Put", "Binocular"};
};
class GVAR(shadow_company_rhsgref_ins_machinegunner) : rhsgref_ins_machinegunner {
	displayName = "Machinegunner";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_rhsgref_ins_machinegunner.jpg);
	faction = QGVAR(shadow_company);
	items[] = {"FirstAidKit", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_Canteen", "ACE_Flashlight_MX991"};
	linkedItems[] = {"VSM_LBT6094_MG_OGA", "ItemMap", "TFAR_anprc152", "ItemWatch", "ItemCompass", "VSM_balaclava_Black", "rhsusf_ANPVS_15", "VSM_fasthelmet_tan"};
	magazines[] = {"SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_m67", "rhs_mag_m67", "rhsusf_100Rnd_762x51_m62_tracer", "rhsusf_100Rnd_762x51_m62_tracer", "rhsusf_100Rnd_762x51_m62_tracer", "rhsusf_100Rnd_762x51_m62_tracer", "rhsusf_100Rnd_762x51_m62_tracer", "rhsusf_100Rnd_762x51_m62_tracer"};
	respawnItems[] = {"FirstAidKit", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_Canteen", "ACE_Flashlight_MX991"};
	respawnLinkedItems[] = {"VSM_LBT6094_MG_OGA", "ItemMap", "TFAR_anprc152", "ItemWatch", "ItemCompass", "VSM_balaclava_Black", "rhsusf_ANPVS_15", "VSM_fasthelmet_tan"};
	respawnMagazines[] = {"SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_m67", "rhs_mag_m67", "rhsusf_100Rnd_762x51_m62_tracer", "rhsusf_100Rnd_762x51_m62_tracer", "rhsusf_100Rnd_762x51_m62_tracer", "rhsusf_100Rnd_762x51_m62_tracer", "rhsusf_100Rnd_762x51_m62_tracer", "rhsusf_100Rnd_762x51_m62_tracer"};
	respawnWeapons[] = {"rhs_weap_m240B", "rhsusf_weap_glock17g4", "Laserdesignator", "Throw", "Put", "Binocular"};
	uniformClass = "MLO_OGA_Crye_Black_Camo";
	vehicleClass = "Men";
	weapons[] = {"rhs_weap_m240B", "rhsusf_weap_glock17g4", "Laserdesignator", "Throw", "Put", "Binocular"};
};
class GVAR(shadow_company_O_Soldier_AAR_F) : O_Soldier_AAR_F {
	displayName = "Asst.Machinegunner";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_O_Soldier_AAR_F.jpg);
	faction = QGVAR(shadow_company);
	items[] = {"FirstAidKit", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_Canteen", "ACE_Flashlight_MX991"};
	linkedItems[] = {"VSM_FAPC_Operator_OGA", "ItemMap", "TFAR_anprc152", "ItemWatch", "ItemCompass", "VSM_balaclava_Black", "rhsusf_ANPVS_15", "VSM_fasthelmet_tan"};
	magazines[] = {"SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_m67", "rhs_mag_m67", "rhsusf_100Rnd_762x51_m62_tracer", "rhsusf_100Rnd_762x51_m62_tracer", "rhsusf_100Rnd_762x51_m62_tracer", "rhsusf_100Rnd_762x51_m62_tracer"};
	respawnItems[] = {"FirstAidKit", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_Canteen", "ACE_Flashlight_MX991"};
	respawnLinkedItems[] = {"VSM_FAPC_Operator_OGA", "ItemMap", "TFAR_anprc152", "ItemWatch", "ItemCompass", "VSM_balaclava_Black", "rhsusf_ANPVS_15", "VSM_fasthelmet_tan"};
	respawnMagazines[] = {"SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_m67", "rhs_mag_m67", "rhsusf_100Rnd_762x51_m62_tracer", "rhsusf_100Rnd_762x51_m62_tracer", "rhsusf_100Rnd_762x51_m62_tracer", "rhsusf_100Rnd_762x51_m62_tracer"};
	respawnWeapons[] = {QGVAR(sight_laser_grip_rhs_weap_mk17_CQC), "rhsusf_weap_glock17g4", "Laserdesignator", "Throw", "Put", "Binocular"};
	backpack = "VSM_OGA_Backpack_Kitbag";
	uniformClass = "MLO_OGA_Crye_Black_Camo";
	vehicleClass = "Men";
	weapons[] = {QGVAR(sight_laser_grip_rhs_weap_mk17_CQC), "rhsusf_weap_glock17g4", "Laserdesignator", "Throw", "Put", "Binocular"};
};
class GVAR(shadow_company_O_Soldier_F) : O_Soldier_F {
	displayName = "Rifleman";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_O_Soldier_F.jpg);
	faction = QGVAR(shadow_company);
	items[] = {"FirstAidKit", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_Canteen", "ACE_Flashlight_MX991"};
	linkedItems[] = {"VSM_FAPC_Operator_OGA", "ItemMap", "TFAR_anprc152", "ItemWatch", "ItemCompass", "VSM_balaclava_Black", "rhsusf_ANPVS_15", "VSM_fasthelmet_tan"};
	magazines[] = {"SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_m67", "rhs_mag_m67", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball"};
	respawnItems[] = {"FirstAidKit", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_Canteen", "ACE_Flashlight_MX991"};
	respawnLinkedItems[] = {"VSM_FAPC_Operator_OGA", "ItemMap", "TFAR_anprc152", "ItemWatch", "ItemCompass", "VSM_balaclava_Black", "rhsusf_ANPVS_15", "VSM_fasthelmet_tan"};
	respawnMagazines[] = {"SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_m67", "rhs_mag_m67", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball", "rhs_mag_20Rnd_SCAR_762x51_m80_ball"};
	respawnWeapons[] = {QGVAR(sight_laser_grip_rhs_weap_mk17_CQC), "rhsusf_weap_glock17g4", "Laserdesignator", "Throw", "Put", "Binocular"};
	uniformClass = "MLO_OGA_Crye_Black_Camo";
	vehicleClass = "Men";
	weapons[] = {QGVAR(sight_laser_grip_rhs_weap_mk17_CQC), "rhsusf_weap_glock17g4", "Laserdesignator", "Throw", "Put", "Binocular"};
};
class GVAR(shadow_company_O_Soldier_F_s) : O_Soldier_F {
	displayName = "Shotgun";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_O_Soldier_F_s.jpg);
	faction = QGVAR(shadow_company);
	items[] = {"FirstAidKit", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_Canteen", "ACE_Flashlight_MX991"};
	linkedItems[] = {"VSM_FAPC_Breacher_OGA", "ItemMap", "TFAR_anprc152", "ItemWatch", "ItemCompass", "VSM_balaclava_Black", "rhsusf_ANPVS_15", "VSM_fasthelmet_tan"};
	magazines[] = {"SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_m67", "rhs_mag_m67", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck"};
	respawnItems[] = {"FirstAidKit", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_Canteen", "ACE_Flashlight_MX991"};
	respawnLinkedItems[] = {"VSM_FAPC_Breacher_OGA", "ItemMap", "TFAR_anprc152", "ItemWatch", "ItemCompass", "VSM_balaclava_Black", "rhsusf_ANPVS_15", "VSM_fasthelmet_tan"};
	respawnMagazines[] = {"SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_m67", "rhs_mag_m67", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck", "rhsusf_5Rnd_00Buck"};
	respawnWeapons[] = {"rhs_weap_M590_5RD", "rhsusf_weap_glock17g4", "Laserdesignator", "Throw", "Put", "Binocular"};
	uniformClass = "MLO_OGA_Crye_Black_Camo";
	vehicleClass = "Men";
	weapons[] = {"rhs_weap_M590_5RD", "rhsusf_weap_glock17g4", "Laserdesignator", "Throw", "Put", "Binocular"};
};
class GVAR(shadow_company_O_soldier_M_F) : O_soldier_M_F {
	displayName = "Marksman";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_O_soldier_M_F.jpg);
	faction = QGVAR(shadow_company);
	items[] = {"FirstAidKit", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_Canteen", "ACE_Flashlight_MX991"};
	linkedItems[] = {"VSM_CarrierRig_Operator_OGA", "ItemMap", "TFAR_anprc152", "ItemWatch", "ItemCompass", "VSM_Goggles", "rhsusf_ANPVS_15", "VSM_Bowman_cap_balaclava_Tan"};
	magazines[] = {"SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_m67", "rhs_mag_m67", "ACE_20Rnd_762x51_M993_AP_Mag", "ACE_20Rnd_762x51_M993_AP_Mag", "ACE_20Rnd_762x51_M993_AP_Mag", "ACE_20Rnd_762x51_M993_AP_Mag", "ACE_20Rnd_762x51_M993_AP_Mag", "ACE_20Rnd_762x51_M993_AP_Mag", "ACE_20Rnd_762x51_M993_AP_Mag", "ACE_20Rnd_762x51_M993_AP_Mag", "ACE_20Rnd_762x51_M993_AP_Mag", "ACE_20Rnd_762x51_M993_AP_Mag", "ACE_20Rnd_762x51_M993_AP_Mag"};
	respawnItems[] = {"FirstAidKit", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_Canteen", "ACE_Flashlight_MX991"};
	respawnLinkedItems[] = {"VSM_CarrierRig_Operator_OGA", "ItemMap", "TFAR_anprc152", "ItemWatch", "ItemCompass", "VSM_Goggles", "rhsusf_ANPVS_15", "VSM_Bowman_cap_balaclava_Tan"};
	respawnMagazines[] = {"SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_m67", "rhs_mag_m67", "ACE_20Rnd_762x51_M993_AP_Mag", "ACE_20Rnd_762x51_M993_AP_Mag", "ACE_20Rnd_762x51_M993_AP_Mag", "ACE_20Rnd_762x51_M993_AP_Mag", "ACE_20Rnd_762x51_M993_AP_Mag", "ACE_20Rnd_762x51_M993_AP_Mag", "ACE_20Rnd_762x51_M993_AP_Mag", "ACE_20Rnd_762x51_M993_AP_Mag", "ACE_20Rnd_762x51_M993_AP_Mag", "ACE_20Rnd_762x51_M993_AP_Mag", "ACE_20Rnd_762x51_M993_AP_Mag"};
	respawnWeapons[] = {QGVAR(sight_bipod_rhs_weap_m14ebrri), "rhsusf_weap_glock17g4", "Laserdesignator", "Throw", "Put", "Binocular"};
	uniformClass = "MLO_OGA_Crye_Black_Camo";
	vehicleClass = "Men";
	weapons[] = {QGVAR(sight_bipod_rhs_weap_m14ebrri), "rhsusf_weap_glock17g4", "Laserdesignator", "Throw", "Put", "Binocular"};
};
class GVAR(shadow_company_O_helipilot_F) : O_helipilot_F {
	displayName = "Heli Pilot";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_O_helipilot_F.jpg);
	faction = QGVAR(shadow_company);
	items[] = {"FirstAidKit", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_Canteen", "ACE_Flashlight_MX991"};
	linkedItems[] = {"VSM_OGA_IOTV_1", "ItemMap", "TFAR_anprc152", "ItemWatch", "ItemCompass", "VSM_balaclava2_Black", "rhsusf_ANPVS_15", "rhsusf_hgu56p_visor_black"};
	magazines[] = {"SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_m67", "rhs_mag_m67"};
	respawnItems[] = {"FirstAidKit", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_Canteen", "ACE_Flashlight_MX991"};
	respawnLinkedItems[] = {"VSM_OGA_IOTV_1", "ItemMap", "TFAR_anprc152", "ItemWatch", "ItemCompass", "VSM_balaclava2_Black", "rhsusf_ANPVS_15", "rhsusf_hgu56p_visor_black"};
	respawnMagazines[] = {"SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_m67", "rhs_mag_m67"};
	respawnWeapons[] = {"UK3CB_MP5K", "rhsusf_weap_glock17g4", "Laserdesignator", "Throw", "Put", "Binocular"};
	uniformClass = "MLO_OGA_Crye_Black_Camo";
	vehicleClass = "Men";
	weapons[] = {"UK3CB_MP5K", "rhsusf_weap_glock17g4", "Laserdesignator", "Throw", "Put", "Binocular"};
};
class GVAR(shadow_company_O_crew_F) : O_crew_F {
	displayName = "Vehicle Crew";
	editorSubcategory = "EdSubcat_Personnel";
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_O_crew_F.jpg);
	faction = QGVAR(shadow_company);
	items[] = {"FirstAidKit", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_Canteen", "ACE_Flashlight_MX991"};
	linkedItems[] = {"VSM_OGA_IOTV_1", "ItemMap", "TFAR_anprc152", "ItemWatch", "ItemCompass", "VSM_balaclava2_Black", "O_NVGoggles_grn_F", "H_HelmetCrew_B"};
	magazines[] = {"SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_m67", "rhs_mag_m67"};
	respawnItems[] = {"FirstAidKit", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_elasticBandage", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_Canteen", "ACE_Flashlight_MX991"};
	respawnLinkedItems[] = {"VSM_OGA_IOTV_1", "ItemMap", "TFAR_anprc152", "ItemWatch", "ItemCompass", "VSM_balaclava2_Black", "O_NVGoggles_grn_F", "H_HelmetCrew_B"};
	respawnMagazines[] = {"SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShell", "rhs_mag_m67", "rhs_mag_m67"};
	respawnWeapons[] = {"UK3CB_MP5K", "rhsusf_weap_glock17g4", "Laserdesignator", "Throw", "Put", "Binocular"};
	uniformClass = "MLO_OGA_Crye_Black_Camo";
	vehicleClass = "Men";
	weapons[] = {"UK3CB_MP5K", "rhsusf_weap_glock17g4", "Laserdesignator", "Throw", "Put", "Binocular"};
};

class GVAR(shadow_company_UK3CB_ION_O_Desert_Dingo) : UK3CB_ION_O_Desert_Dingo {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_UK3CB_ION_O_Desert_Dingo.jpg);
	crew = QGVAR(shadow_company_O_Soldier_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_Soldier_F)};
};
class GVAR(shadow_company_UK3CB_ION_O_Desert_MaxxPro_M2) : UK3CB_ION_O_Desert_MaxxPro_M2 {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_UK3CB_ION_O_Desert_MaxxPro_M2.jpg);
	crew = QGVAR(shadow_company_O_Soldier_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_Soldier_F)};
};
class GVAR(shadow_company_UK3CB_ION_O_Desert_Offroad) : UK3CB_ION_O_Desert_Offroad {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_UK3CB_ION_O_Desert_Offroad.jpg);
	crew = QGVAR(shadow_company_O_Soldier_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_Soldier_F)};
};
class GVAR(shadow_company_UK3CB_ION_O_Desert_Offroad_Covered) : UK3CB_ION_O_Desert_Offroad_Covered {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_UK3CB_ION_O_Desert_Offroad_Covered.jpg);
	crew = QGVAR(shadow_company_O_Soldier_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_Soldier_F)};
};
class GVAR(shadow_company_UK3CB_ION_O_Desert_LSV_02_Armed) : UK3CB_ION_O_Desert_LSV_02_Armed {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_UK3CB_ION_O_Desert_LSV_02_Armed.jpg);
	crew = QGVAR(shadow_company_O_Soldier_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_Soldier_F)};
};
class GVAR(shadow_company_UK3CB_ION_O_Desert_LSV_02) : UK3CB_ION_O_Desert_LSV_02 {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_UK3CB_ION_O_Desert_LSV_02.jpg);
	crew = QGVAR(shadow_company_O_Soldier_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_Soldier_F)};
};
class GVAR(shadow_company_UK3CB_ION_O_Desert_M113_M2) : UK3CB_ION_O_Desert_M113_M2 {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_UK3CB_ION_O_Desert_M113_M2.jpg);
	crew = QGVAR(shadow_company_O_crew_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_crew_F)};
};
class GVAR(shadow_company_UK3CB_ION_O_Desert_T810_Reammo) : UK3CB_ION_O_Desert_T810_Reammo {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_UK3CB_ION_O_Desert_T810_Reammo.jpg);
	crew = QGVAR(shadow_company_O_Soldier_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_Soldier_F)};
};
class GVAR(shadow_company_UK3CB_ION_O_Desert_T810_Refuel) : UK3CB_ION_O_Desert_T810_Refuel {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_UK3CB_ION_O_Desert_T810_Refuel.jpg);
	crew = QGVAR(shadow_company_O_Soldier_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_Soldier_F)};
};
class GVAR(shadow_company_UK3CB_ION_O_Desert_T810_Recovery) : UK3CB_ION_O_Desert_T810_Recovery {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_UK3CB_ION_O_Desert_T810_Recovery.jpg);
	crew = QGVAR(shadow_company_O_Soldier_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_Soldier_F)};
};
class GVAR(shadow_company_UK3CB_ION_O_Desert_T810_Repair) : UK3CB_ION_O_Desert_T810_Repair {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_UK3CB_ION_O_Desert_T810_Repair.jpg);
	crew = QGVAR(shadow_company_O_Soldier_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_Soldier_F)};
};
class GVAR(shadow_company_UK3CB_ION_B_Desert_T810_Closed) : UK3CB_ION_B_Desert_T810_Closed {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_UK3CB_ION_B_Desert_T810_Closed.jpg);
	crew = QGVAR(shadow_company_O_Soldier_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_Soldier_F)};
};
class GVAR(shadow_company_UK3CB_ION_B_Urban_M240_High) : UK3CB_ION_B_Urban_M240_High {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_UK3CB_ION_B_Urban_M240_High.jpg);
	crew = QGVAR(shadow_company_O_Soldier_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_Soldier_F)};
};
class GVAR(shadow_company_UK3CB_ION_B_Urban_M240_Low) : UK3CB_ION_B_Urban_M240_Low {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_UK3CB_ION_B_Urban_M240_Low.jpg);
	crew = QGVAR(shadow_company_O_Soldier_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_Soldier_F)};
};
class GVAR(shadow_company_UK3CB_ION_B_Urban_M252) : UK3CB_ION_B_Urban_M252 {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_UK3CB_ION_B_Urban_M252.jpg);
	crew = QGVAR(shadow_company_O_Soldier_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_Soldier_F)};
};
class GVAR(shadow_company_UK3CB_ION_B_Urban_M2_TriPod) : UK3CB_ION_B_Urban_M2_TriPod {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_UK3CB_ION_B_Urban_M2_TriPod.jpg);
	crew = QGVAR(shadow_company_O_Soldier_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_Soldier_F)};
};
class GVAR(shadow_company_UK3CB_ION_B_Urban_M2_MiniTripod) : UK3CB_ION_B_Urban_M2_MiniTripod {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_UK3CB_ION_B_Urban_M2_MiniTripod.jpg);
	crew = QGVAR(shadow_company_O_Soldier_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_Soldier_F)};
};
class GVAR(shadow_company_UK3CB_ION_B_Urban_M240_nest) : UK3CB_ION_B_Urban_M240_nest {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_UK3CB_ION_B_Urban_M240_nest.jpg);
	crew = QGVAR(shadow_company_O_Soldier_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_Soldier_F)};
};
class GVAR(shadow_company_RHS_Stinger_AA_pod_D) : RHS_Stinger_AA_pod_D {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_RHS_Stinger_AA_pod_D.jpg);
	crew = QGVAR(shadow_company_O_Soldier_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_Soldier_F)};
};
class GVAR(shadow_company_RHS_TOW_TriPod_D) : RHS_TOW_TriPod_D {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_RHS_TOW_TriPod_D.jpg);
	crew = QGVAR(shadow_company_O_Soldier_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_Soldier_F)};
};
class GVAR(shadow_company_RHS_M119_D) : RHS_M119_D {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_RHS_M119_D.jpg);
	crew = QGVAR(shadow_company_O_Soldier_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_Soldier_F)};
};
class GVAR(shadow_company_UK3CB_ION_B_Desert_MELB_AH6M) : UK3CB_ION_B_Desert_MELB_AH6M {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_UK3CB_ION_B_Desert_MELB_AH6M.jpg);
	crew = QGVAR(shadow_company_O_helipilot_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_helipilot_F)};
};
class GVAR(shadow_company_UK3CB_ION_B_Desert_Bell412_Utility) : UK3CB_ION_B_Desert_Bell412_Utility {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_UK3CB_ION_B_Desert_Bell412_Utility.jpg);
	crew = QGVAR(shadow_company_O_helipilot_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_helipilot_F)};
};
class GVAR(shadow_company_UK3CB_ION_B_Desert_MELB_MH6M) : UK3CB_ION_B_Desert_MELB_MH6M {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_UK3CB_ION_B_Desert_MELB_MH6M.jpg);
	crew = QGVAR(shadow_company_O_helipilot_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_helipilot_F)};
};
class GVAR(shadow_company_UK3CB_ION_B_Desert_UH1H_GUNSHIP) : UK3CB_ION_B_Desert_UH1H_GUNSHIP {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_UK3CB_ION_B_Desert_UH1H_GUNSHIP.jpg);
	crew = QGVAR(shadow_company_O_helipilot_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_helipilot_F)};
};
class GVAR(shadow_company_UK3CB_ION_B_Urban_Cessna_T41_Armed_M134) : UK3CB_ION_B_Urban_Cessna_T41_Armed_M134 {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_UK3CB_ION_B_Urban_Cessna_T41_Armed_M134.jpg);
	crew = QGVAR(shadow_company_O_helipilot_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_helipilot_F)};
};
class GVAR(shadow_company_rhsusf_f22) : rhsusf_f22 {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_rhsusf_f22.jpg);
	crew = QGVAR(shadow_company_O_helipilot_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_helipilot_F)};
};
class GVAR(shadow_company_RHS_C130J) : RHS_C130J {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_RHS_C130J.jpg);
	crew = QGVAR(shadow_company_O_helipilot_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_helipilot_F)};
};
class GVAR(shadow_company_RHS_C130J_Cargo) : RHS_C130J_Cargo {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_RHS_C130J_Cargo.jpg);
	crew = QGVAR(shadow_company_O_helipilot_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_helipilot_F)};
};
class GVAR(shadow_company_RHS_A10) : RHS_A10 {
	editorPreview = QPATHTOF(data\editorPreviews\shadow_company_RHS_A10.jpg);
	crew = QGVAR(shadow_company_O_helipilot_F);
	faction = QGVAR(shadow_company);
	side = 0;
	typicalCrew[] = {QGVAR(shadow_company_O_helipilot_F)};
};
